# Generated by Django 5.1.6 on 2025-02-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('T', 'Teddy'), ('W', 'Watch'), ('P', 'Perfume')], max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=2855)),
            ],
        ),
    ]
