# Generated by Django 5.1.6 on 2025-03-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_slider_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
