# Generated by Django 5.1.6 on 2025-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
