# Generated by Django 5.1.6 on 2025-03-24 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='total',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('amount', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
            preserve_default=False,
        ),
    ]
