# Generated by Django 5.1.6 on 2025-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_user_username_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='2025-04-12', max_length=100),
            preserve_default=False,
        ),
    ]
