# Generated by Django 5.1.6 on 2025-04-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_broadcastnotification_delete_adminmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastnotification',
            options={},
        ),
    ]
