# Generated by Django 3.2.25 on 2025-04-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_broadcastnotification_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BroadcastNotification',
        ),
    ]
